services:
  giant-mall:
    build:
      context: .
      dockerfile: Dockerfile
    image: giant-mall:latest
    container_name: giant-mall
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - .env

  mysql:
    image: mysql:8.0.42
    container_name: giant-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
volumes:
  mysql_data: