spring:
  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

  properties:
    hibernate:
      format_sql: true

springdoc:
  swagger-ui:
    with-credentials: true

jwt:
  secret: V2hhdElzVGhpc1NlY3JldEtleUZvckpXVEF1dGhlbnRpY2F0aW9uPw==
  token-validity-in-seconds: 86400 # 24시간

logging:
  level:
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
    io.swagger.v3: DEBUG